#!/usr/bin/env ruby
message_file = ARGV[0]
message = File.read(message_file, :encoding => Encoding::UTF_8)

current_branch = `git branch | grep '*'`.chomp.sub('* ', '')

if current_branch.include?("/")
  current_branch = current_branch[current_branch.rindex("/")+1 .. current_branch.length]
end

if message.include?("#a")
  message = "[add]"      + message.sub(/#a/, '')
elsif message.include?("#f")
  message = "[feature]"  + message.sub(/#f/, '')
elsif message.include?("#b")
  message = "[bugfix]"   + message.sub(/#b/, '')
elsif message.include?("#r")
  message = "[remove]"   + message.sub(/#r/, '')
end

message = "[" + current_branch + "]" + message

File.write(message_file, message)
